### ISSUE TITLE
#undefined on path 

### ISSUE THREAD

**Issue by cesardmoro** [sue445/chrome-gitlab-notifier#120]
i have this error: 
when getting nofitication has undefined on it and url does not work: 
gitlabrepourl/desarrollo/project/issues/#undefined

![image](https://user-images.githubusercontent.com/8697604/30178217-93196b00-93de-11e7-9dad-dfda53df9623.png)

**Comment by sue445** [comment]
@cesardmoro Please tell me the followings.

* GitLab version
* API endpoint (v3 or v4)

**Comment by cesardmoro** [comment]
@sue445  this : 
gitlab 9.2.2
api v4

**Comment by sue445** [comment]
@cesardmoro Sorry, API v4 requires GitLab **v9.5.0+**
https://github.com/sue445/chrome-gitlab-notifier/blob/2.1.1/README.md#api-v4

Please upgrade to v9.5.0+ or use v3 endpoint
