### ISSUE TITLE
Ignore own events

### ISSUE THREAD

**Issue by kaplun** [sue445/chrome-gitlab-notifier#152]
It would be great if there was an option to not consider those events generated by the same user who owns the token. E.g. each time I comment on a repo I monitor I receive a notification, but that is in general not useful.

Thanks a lot for the awesome work!

**Comment by 1u** [comment]
8 :+1:  thubs up... 🎉 :tada: I would love to see that!

**Comment by ghostry** [comment]
I want to see only what I am involved in.

**Comment by sue445** [comment]
I released as `v2.5.0` but currently under reviewing
