### ISSUE TITLE
Clicking a link gives a double-slash URL

### ISSUE THREAD

**Issue by MLefebvreICO** [sue445/chrome-gitlab-notifier#177]
Hi there,

Just found out that if I click on a Merge Request in the plugin, it will open the link with two slash which causes GitLab to misbehave after. I tried with a slash when ending the base URL and without a slash, both gives a wrong link.

### Expectation
https://foo.githost.io/Project-Space/Some-Repo/merge_requests/3672

### What happened
https://foo.githost.io//Project-Space/Some-Repo/merge_requests/3672

**Comment by sue445** [comment]
@MLefebvreICO What is your version of GitLab server?

Plugin generates two slash continuous url, but GitLab works.

e.g) https://gitlab.com//sue445/gitlab_example/merge_requests/28 is redirect to https://gitlab.com/sue445/gitlab_example/merge_requests/28

**Comment by MLefebvreICO** [comment]
@sue445 GitLab CE 11.1.4

On this version, if you run a URL with two slashes, it just keeps them and make certain pages inaccessible

**Comment by sue445** [comment]
@MLefebvreICO I see. I will fix this.

**Comment by sue445** [comment]
@MLefebvreICO I fixed this problem and released v2.3.1 to webstore

**Comment by MLefebvreICO** [comment]
@sue445 I can confirm that it is now working as intended. Thanks 😄
