### ISSUE TITLE
Error when pushing save button

### ISSUE THREAD

**Issue by goroya** [sue445/chrome-gitlab-notifier#493]
![Screenshot from 2020-03-21 16-00-32](https://user-images.githubusercontent.com/28487609/77221457-34e1de80-6b8d-11ea-89c5-9d57bb82a6fe.png)

Plugin occur error when pushing save button after inputing  token and url.
So I cannot use your plugin.  

```
[versions]

version 2.5.0 
chrome verison is Version 80.0.3987.149 (Official Build) (64-bit)

```

**Comment by sue445** [comment]
@goroya Sorry! I fixed at `v2.5.1`
