### ISSUE TITLE
Ignore myself activity

### ISSUE THREAD

**Issue by hotoo** [sue445/chrome-gitlab-notifier#60]
When I post a new issue, or some others activities, do'nt notify me please :)

**Comment by sue445** [comment]
Please show me your settings.

**Comment by hotoo** [comment]
![0](https://cloud.githubusercontent.com/assets/143572/8369298/e492ec0a-1be9-11e5-8b47-ddfa36dbf665.png)
![1](https://cloud.githubusercontent.com/assets/143572/8369299/ee990fcc-1be9-11e5-90b2-889c36307f55.png)
![2](https://cloud.githubusercontent.com/assets/143572/8369302/f35c0802-1be9-11e5-84ce-02eb936475a1.png)

**Comment by sue445** [comment]
Which version of do you use GitLab?

**Comment by hotoo** [comment]
The master branch from github.

**Comment by sue445** [comment]
Sorry, I was mistaken. 

I thought this is bug report, but this is question.

>  do'nt notify me please

Uncheck checkbox (Commit, Issue, MergeRequest or Milestone) in configuration.

**Comment by hotoo** [comment]
I mean, when have others people (not mine) activities, notify me.
If the activity is from myself, don't notify me please.

**Comment by sue445** [comment]
I think this is nice idea.
I'll make it someday

**Comment by hotoo** [comment]
I make [GitLab Notifications](https://github.com/hotoo/gitlab-notifications) do this,

Thanks for you idea.
