### ISSUE TITLE
Support multiple account

### ISSUE THREAD

**Issue by hotoo** [sue445/chrome-gitlab-notifier#61]
I have 2 private gitlab account, the company and sub-company network is connected, but have two gitlab. like:

* http://gitlab.company.com/
* http://gitlab.sub-company.com/

**Comment by sue445** [comment]
It's a good idea, but I don't use multiple account.

I'm accepting your pull request every time

**Comment by hotoo** [comment]
I make [GitLab Notifications](https://github.com/hotoo/gitlab-notifications) do this,

Thanks for you idea.

**Comment by sue445** [comment]
👍 👍 👍
