### ISSUE TITLE
Intranet GitLab no notification

### ISSUE THREAD

**Issue by NMathar** [sue445/chrome-gitlab-notifier#64]
/////////// DUPLICATE TO CHROMESTORE PROBLEM /////////////

Hi,

i have an internal hosted GitLab and i get the reposirorylist but no notifications.

Is that right or still a configuration issue?

**Comment by NMonst4** [comment]
Ok not all notifications are displayed sometimes one is shown.

**Comment by NMonst4** [comment]
OK.

Now commits send notifications but on issue creation theres is no nitification.

**Comment by sue445** [comment]
@NMonst4 Please show me your configuration and gitlab version

**Comment by NMonst4** [comment]
GitLab 7.9.0

![bildschirmfoto 2015-07-22 um 19 02 10](https://cloud.githubusercontent.com/assets/8554558/8831690/487275c8-30a4-11e5-8e7a-eedb4197ee2b.png)
![bildschirmfoto 2015-07-22 um 19 02 20](https://cloud.githubusercontent.com/assets/8554558/8831694/4d462860-30a4-11e5-8423-247fe92d9595.png)

**Comment by sue445** [comment]
@NMonst4 I'm sorry answer is too slow.

I don't know waht is wrong ... (it seems right )

**Comment by NMonst4** [comment]
@sue445 Strange but i get still only notification for commits nothing else. :( When i get time to code review i will look at these strange issue on my client.
