### ISSUE TITLE
(Optionally) display new logo

### ISSUE THREAD

**Issue by xasx** [sue445/chrome-gitlab-notifier#65]
GitLab recently introduced a new logo.

For those who are already on new versions, it would be great to have at least a config which allows to display the new logo instead of the old - for visual association.

Find the source SVG here: https://github.com/gitlabhq/gitlabhq/blob/master/app/assets/images/logo.svg

Thanks.

**Comment by xasx** [comment]
Find a converted PNG attached.

![logo](https://cloud.githubusercontent.com/assets/1582730/9034685/f0cd9ffa-39d1-11e5-9e73-8589447a9a53.png)

**Comment by sue445** [comment]
thx! I had forgotten that the logo had changed

**Comment by sue445** [comment]
@xasx I changed to new GitLab icon ( #66 ) and release as `v1.2.1` 

Thank you for teaching !

**Comment by xasx** [comment]
Thanks, verified: works :+1:

**Comment by sue445** [comment]
:smiley:
