### ISSUE TITLE
Toggle all/none on Repository Events doesn't consider the filter

### ISSUE THREAD

**Issue by cr0cK** [sue445/chrome-gitlab-notifier#67]
Hi,

Il you set a filter, then click on `All` to check all the events of the filtered projects, it selects the events for all the projects (not the filtered ones). I think it's not the behavior expected.

**Comment by sue445** [comment]
Indeed !
This should be fixed

**Comment by sue445** [comment]
This problem will be fixed at next major version v2.0.0. (fixed at `develop-2.0` branch)
