### ISSUE TITLE
Support "commented on" in project event

### ISSUE THREAD

**Issue by sue445** [sue445/chrome-gitlab-notifier#74]
for Gitlab v8.3.0+

* https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/projects.md#get-project-events
* https://github.com/gitlabhq/gitlabhq/commit/3227a5ead22c90873794b0c0e4c788436283fb3e

**Comment by hotoo** [comment]
+1

**Comment by yhl3692319** [comment]
+1

**Comment by Nkzn** [comment]
+1

**Comment by sue445** [comment]
Release v1.4.0 !
