### ISSUE TITLE
Problem with date format ?

### ISSUE THREAD

**Issue by Ihryll** [sue445/chrome-gitlab-notifier#75]
Hi,

I just push a commit today (06/01/2016, french format) and the popup indicated that the commit was 5 month old (as if the today date was 01/06/2016, english format).

To I miss an option in chrome-gitlab-notifier or in GitLab configuration ?

Regards,
![gitlab notifier date](https://cloud.githubusercontent.com/assets/7593827/12137623/8e1ed8d2-b452-11e5-8cc4-dd53a6e95311.png)

**Comment by sue445** [comment]
@Ihryll hmmm...

I think this is because of the difference in the behavior of `Date#toLocaleString()`

# Example
I'm using Japan format timestamp 

```javascript
config.getNotifiedHistories()[0].notified_at
// => "2016-01-06T14:16:55.432Z"

new Date(config.getNotifiedHistories()[0].notified_at).toLocaleString()
// => "2016/1/6 23:16:55"
```

[jquery-timeago](https://github.com/rmm5t/jquery-timeago) does not support french format timestamp :crying_cat_face: 

I'll fix this problem

**Comment by sue445** [comment]
@Ihryll I fixed at #77 . Please next version :bow:

**Comment by Ihryll** [comment]
Great ! Thanks !

**Comment by sue445** [comment]
Release v1.4.0 !

**Comment by lejoko** [comment]
For me the problem is still there with 1.4.0

**Comment by FlorianBruniaux** [comment]
Same issue.

It says that the notification is 8 months ago but it was a few minutes ago.
Date format 11/3/2016 11:05:55

<img width="437" alt="capture d ecran 2016-03-11 a 11 10 44" src="https://cloud.githubusercontent.com/assets/3902606/13699345/11c9da88-e77a-11e5-928b-90629bfe2bae.png">

**Comment by sue445** [comment]
@lejoko @FlorianBruniaux Hmmm...

Please tell me your timezone.

## example
Input chrome web inspector console

```javascript
var date = new Date();

date.toString(); 
// => "Fri Mar 11 2016 19:17:14 GMT+0900 (JST)"

date.toLocaleString()
// => "2016/3/11 19:17:14"
```

**Comment by FlorianBruniaux** [comment]
For me, France / Paris -> GMT +1
http://wwp.greenwichmeantime.com/time-zone/europe/european-union/france/paris/

**Comment by lejoko** [comment]
My timezone is Asia/Jerusalem

The output you requested is:
```javascript
var date = new Date();
// => undefined

date.toString();
// => "Sun Mar 13 2016 08:31:58 GMT+0200 (IST)"

date.toLocaleString()
// => "13/3/2016 08:31:58"
```

**Comment by sue445** [comment]
hmm...

I want to fix.
But I can not fix this problem really, because this problem is not reproduced in my environment (I'm using JST)

Please fix and PR me

**Comment by lejoko** [comment]
Great! Thanks for the merge! Do you have an idea when you will publish a new version? (my teammates are waiting for the bugfix...)

**Comment by sue445** [comment]
>  (my teammates are waiting for the bugfix...)

@lejoko Great thanks! I'll release next version soon !

**Comment by sue445** [comment]
I upload `v1.4.1` to developer dashboard. Please wait
