### ISSUE TITLE
issue links lead to 404

### ISSUE THREAD

**Issue by mbunkus** [sue445/chrome-gitlab-notifier#774]
I have my repositories on the public gitlab.com site. Starting today (or a couple of days ago at most) issue links displayed by the extension yield in a 404. It seems that gitlab.com has finally made the `…/-/…` part in the links mandatory.

This is the link the extension creates:

https://gitlab.com/mbunkus/mkvtoolnix/issues/3545

Here's the actually working link:

https://gitlab.com/mbunkus/mkvtoolnix/-/issues/3545

**Comment by sue445** [comment]
Now, chrome-gitlab-notifier supports GitLab 16.0+ since v2.6.0

* #778
* https://github.com/sue445/chrome-gitlab-notifier/blob/master/CHANGELOG.md#260-20230520

I uploaded package to Chrome Webstore. New version will be available after Google's review is complete.

**Comment by mbunkus** [comment]
Thank you very much!
