### ISSUE TITLE
Showing too many old notifications

### ISSUE THREAD

**Issue by kujiy** [sue445/chrome-gitlab-notifier#85]
Thank you for sharing your cool tool.

Since I've started to use this, it's sent a notification of the latest activity with all of past activities of the project what was updated just at that time. So that I get lots of old notifications everytime. What's wrong?

**Comment by sue445** [comment]
@kujiy Thank you.

I know this problem.  `chrome-gitlab-notifier` has caching for notified event, but this is not good 😿
